# Generated by Django 5.0.2 on 2024-02-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
